# Generated by Django 5.2.3 on 2025-06-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.lease'),
        ),
    ]
