# Generated by Django 5.2.3 on 2025-06-26 18:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='leases/'),
        ),
    ]
