# Generated by Django 5.2.3 on 2025-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
